chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
  path('<int:id>/', views.detail, name="detail"),
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
  path('', views.home, name="home"),
  path('signup/', views.signup, name="signup"),
  path('login/', auth_views.LoginView.as_view(template_name="core/login.html"), name="login"),
  path('logout/', auth_views.LogoutView.as_view(), name="logout"),
]

marketplace/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('products/', include('product.urls')),
    path('me/', include('me.urls')),
    path('chat/', include('chat.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

me/urls.py
from django.urls import path

from . import views

app_name = 'me'

urlpatterns = [
  path('products/', views.products, name="products"),
  path('chats/', views.chats, name="chats"),
]

product/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
  path('<int:id>/', views.detail, name="detail"),
  path('new/', views.new, name="new"),
]

chat/models.py
from django.db import models

from django.contrib.auth.models import User
from product.models import Product

# Create your models here.
class Chat(models.Model):
  buyer = models.ForeignKey(User, related_name="buyer_chats", on_delete=models.CASCADE)
  seller = models.ForeignKey(User, related_name="seller_chats", on_delete=models.CASCADE)
  product = models.ForeignKey(Product, related_name="product_chats", on_delete=models.CASCADE)
  created_at = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return 'Comprador: ' + self.buyer.username + ' - Vendedor: ' + self.seller.username
  
class Message(models.Model):
  chat = models.ForeignKey(Chat, related_name="messages", on_delete=models.CASCADE)
  user = models.ForeignKey(User, related_name="messages", on_delete=models.CASCADE)
  content = models.TextField()
  date_added = models.DateTimeField(auto_now_add=True)

  class Meta:
    ordering = ('date_added',)

  def __str__(self):
    return self.content

core/models.py
from django.db import models

# Create your models here.

me/models.py
from django.db import models

# Create your models here.

product/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.
class Product(models.Model):
  name = models.CharField(max_length=255)
  description = models.TextField(blank=True, null=True)
  price = models.FloatField()
  image = models.ImageField(upload_to='product_images', blank=True, null=True)
  is_sold = models.BooleanField(default=False)
  created_by = models.ForeignKey(User, related_name='products', on_delete=models.CASCADE)
  created_at = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return self.name

core/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
  class Meta:
    model = User
    fields = ['username', 'password1', 'password2']

product/forms.py
from django import forms
from .models import Product

INPUT_CLASSES = 'w-full mt-2 px-4 py-2 rounded-xl'

class NewProductForm(forms.ModelForm):
  class Meta:
    model = Product
    fields = ('name', 'description', 'price', 'image')
    labels = {
      'name': 'Nome',
      'description': 'Descrição',
      'price': 'Preço',
      'image': 'Imagem'
    }

    widgets = {
      'name': forms.TextInput(attrs={
        'class': INPUT_CLASSES
      }),
      'description': forms.Textarea(attrs={
        'class': INPUT_CLASSES
      }),
      'price': forms.TextInput(attrs={
        'class': INPUT_CLASSES
      }),
      'image': forms.FileInput(attrs={
        'class': INPUT_CLASSES
      }),
    }

class EditProductForm(forms.ModelForm):
  class Meta:
    model = Product
    fields = ('name', 'description', 'price', 'image', 'is_sold')

chat/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist

from product.models import Product
from .models import Chat, Message

# Create your views here.
@login_required
def detail(request, id):
  buyerUsername = request.GET.get('buyer')

  product = Product.objects.get(pk=id)
  buyer = User.objects.get(username=buyerUsername)
  user = request.user
  creator_of_product = product.created_by

  messages = None
  chat = None

  try:
    chat = Chat.objects.get(product=product, seller=creator_of_product, buyer=buyer)

    messages = Message.objects.filter(chat=chat)
  except ObjectDoesNotExist:
    chat = Chat(buyer=user, seller=product.created_by, product=product)
    chat.save()


  return render(request, 'chat/index.html', {
    'product': product,
    'chat': chat,
    'messages': messages
  })

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login

from .forms import SignupForm

from product.models import Product

# Create your views here.
def home(request):
  products = Product.objects.all()

  return render(request, 'core/home.html', {
    'products': products
  })

def signup(request):
  if request.method == 'POST':
    form = SignupForm(request.POST)

    if form.is_valid():
      user = form.save()

      login(request, user)

      return redirect('home')

  return render(request, 'core/signup.html')

me/views.py
from django.shortcuts import render
from django.db.models import Q

from product.models import Product
from chat.models import Chat

# Create your views here.
def products(request):
  products = Product.objects.filter(created_by=request.user)

  return render(request, 'me/products.html', {
    'products': products
  })

def chats(request):
  chats = Chat.objects.filter(Q(buyer=request.user) | Q(seller=request.user))

  return render(request, 'me/chats.html', {
    'chats': chats
  })

product/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .forms import NewProductForm
from .models import Product

def detail(request, id):
  product = Product.objects.get(pk=id)

  return render(request, 'product/detail.html', {
    'product': product
  })

# Create your views here.
@login_required
def new(request):
  if request.method == 'POST':
    form = NewProductForm(request.POST, request.FILES)

    if form.is_valid():
      item = form.save(commit=False)
      item.created_by = request.user
      item.save()

      return redirect('home')
  else:
    form = NewProductForm()

  return render(request, 'product/form.html', {
    'form': form,
    'title': 'Novo produto'
  })

chat/templates/chat/index.html
{% extends 'core/base.html' %}

{% block title %}{{ product.name }}{% endblock %}

{% block content %}
<div class="flex flex-col justify-center items-center py-6">
  <div class="text-center mb-4">
    <h1 class="text-2xl lg:text-3xl text-white">{{ product.name }}</h1>
    {% if request.user == product.created_by %}
      <p class="text-white mt-2">Você está vendendo esse produto.</p>
    {% else %}
      <p class="text-white mt-2">Vendedor: {{ product.created_by.username }}</p>
    {% endif %}
  </div>

  <div class="w-full max-w-[500px] mx-4 mx-auto p-4 bg-white rounded-xl">
    <div class="chat-messages space-y-3" id="chat-messages">
      {% for message in messages %}
        <div class="p-4 bg-gray-200 rounded-xl">
          <p class="font-semibold">{{ message.user }}</p>
          <p>{{ message.content }}</p>
        </div>
      {% endfor %}
    </div>
  </div>

  <div class="w-full max-w-[500px] mt-6 mx-4 lg:mx-auto p-4 bg-white rounded-xl">
    <form method="POST" action="." class="flex">
      <input type="text" name="content" class="flex-1 mr-3 outline-none" placeholder="Your message..." id="chat-message-input">

      <button class="px-5 py-3 rounded-xl text-white bg-teal-600 hover:bg-teal-700" id="chat-message-submit">Submit</button>
    </form>
  </div>
</div>
{% endblock %}

{% block scripts %}
{{ chat.id|json_script:"json-chatid" }}
{{ request.user.username|json_script:"json-buyer" }}

<script>
  const chatId = JSON.parse(document.getElementById('json-chatid').textContent)
  const buyer = JSON.parse(document.getElementById('json-buyer').textContent)

  const chatSocket = new WebSocket(`ws://${window.location.host}/ws/${chatId}/`)
  
  chatSocket.onmessage = event => {
    const data = JSON.parse(event.data)

    if (data.message) {
      let html = `
        <div class="p-4 bg-gray-200 rounded-xl">
          <p class="font-semibold">${data.buyer}</p>
          <p>${data.message}</p>
        </div>
      `
      document.querySelector('#chat-messages').innerHTML += html
    } else {
      alert('Message was empty.')
    }

    console.log({ data })
  }
  
  chatSocket.onclose = (event) => {
    console.log('onclose')
  }

  document.getElementById('chat-message-submit').onclick = (event) => {
    event.preventDefault()

    const messageInputDom = document.querySelector('#chat-message-input')
    const message = messageInputDom.value

    chatSocket.send(JSON.stringify({
      'message': message,
      'chatId': chatId,
      'buyer': buyer,
    }))

    messageInputDom.value = ''

    return false
  }
</script>
{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <script src="https://cdn.tailwindcss.com"></script>

  <style>
    .chat-messages {
      height: 400px;
      overflow-y: auto;
    }

    label[for=id_description], label[for=id_name], label[for=id_image], label[for=id_price] {
      color: white;
      margin-bottom: 8px;
    }
  </style>

  <title>{% block title %}{% endblock %} | Chat</title>
</head>
<body class="bg-slate-400">
  <nav class="flex items-center justify-between p-4 bg-slate-700">
    <div>
      <a href="/" class="text-xl text-white">Chat</a>

    </div>
    <div class="flex items-center space-x-4">
      {% if request.user.is_authenticated %}
        <span class="text-white">{{ request.user.username }}</span>
        <a href="/products/new" class="text-white hover:text-gray-200">Novo produto</a>
        <a href="/me/products" class="text-white hover:text-gray-200">Meus produtos</a>
        <a href="/me/chats" class="text-white hover:text-gray-200">Minhas conversas</a>
        <a href="/logout" class="px-5 py-3 rounded-xl text-white bg-teal-600 hover:bg-slate-800">Sair</a>
        {% else %}
        <a href="/login" class="text-white hover:text-gray-200">Login</a>
        <a href="/signup" class="px-5 py-3 rounded-xl text-white bg-slate-600 hover:bg-slate-800">Registrar</a>
      {% endif %}
    </div>
  </nav>

  {% block content %}
  {% endblock %}

  {% block scripts %}
  {% endblock %}
</body>
</html>

core/templates/core/home.html
{% extends 'core/base.html' %}

{% block title %}Início{% endblock %}

{% block content %}
<div class="p-10 flex flex-col">
  <h1 class="text-2xl lg:text-6xl text-white">Início</h1>

  <div class="grid grid-cols-3 gap-5 mt-6">
    {% for product in products %}
      <div class="bg-slate-600 rounded-xl">
        <a href="{% url 'product:detail' product.id %}">
          <div class="flex justify-center">
            <img src="{{ product.image.url }}" class="rounded-t-xl h-[150px]">
          </div>

          <div class="p-6 bg-white rounded-b-xl"> 
            <h2 class="text-2xl">{{ product.name }}</h2>
            <p class="text-gray-500">{{ product.price }}</p>
          </div>
        </a>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="p-10 lg:p-20 text-center">
  <h1 class="text-2xl lg:text-6xl text-white">Login</h1>
</div>

<form method="POST" action="." class="max-w-[400px] px-4 mx-auto">
  {% csrf_token %}

  <div class="mb-5">
    <label class="text-white">Nome de usuário</label>
    <input type="text" name="username" class="w-full mt-2 px-4 py-2 rounded-xl">
  </div>

  <div class="mb-5">
    <label class="text-white">Senha</label>
    <input type="password" name="password" class="w-full mt-2 px-4 py-2 rounded-xl">
  </div>

  {% if form.errors %}
    {% for field in form %}
      {% for error in field.errors %}
        <div class="mb-5 p-4 rounded-xl bg-red-300 text-white">
          <p>{{ error|escape }}</p>
        </div>
      {% endfor %}
    {% endfor %}
  {% endif %}

  <button class="w-full px-5 py-3 rounded-xl text-white bg-slate-600 hover:bg-slate-800">Entrar</button>
</form>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Registre-se{% endblock %}

{% block content %}
<div class="p-10 lg:p-20 text-center">
  <h1 class="text-2xl lg:text-6xl text-white">Registre-se</h1>
</div>

<form method="POST" action="." class="max-w-[400px] px-4 mx-auto">
  {% csrf_token %}

  <div class="mb-5">
    <label class="text-white">Nome de usuário</label>
    <input type="text" name="username" class="w-full mt-2 px-4 py-2 rounded-xl">
  </div>

  <div class="mb-5">
    <label class="text-white">Senha</label>
    <input type="password" name="password1" class="w-full mt-2 px-4 py-2 rounded-xl">
  </div>

  <div class="mb-5">
    <label class="text-white">Repetir senha</label>
    <input type="password" name="password2" class="w-full mt-2 px-4 py-2 rounded-xl">
  </div>

  {% if form.errors %}
    {% for field in form %}
      {% for error in field.errors %}
        <div class="mb-5 p-4 rounded-xl bg-red-300 text-white">
          <p>{{ error|escape }}</p>
        </div>
      {% endfor %}
    {% endfor %}
  {% endif %}

  <button class="w-full px-5 py-3 rounded-xl text-white bg-slate-600 hover:bg-slate-800">Registrar</button>
</form>
{% endblock %}

me/templates/me/chats.html
{% extends 'core/base.html' %}

{% block title %}Meus chats{% endblock %}

{% block content %}
<div class="p-10 flex flex-col">
  <h1 class="text-2xl lg:text-6xl text-white">Meus chats</h1>

  <div class="grid grid-cols-3 gap-5 mt-6">
    {% for chat in chats %}
      <div class="bg-slate-600 rounded-xl">
        <a href="{% url 'chat:detail' chat.product.id %}?buyer={{ chat.buyer.username }}" target="_self">
          <div class="flex justify-center">
            <img src="{{ chat.product.image.url }}" class="rounded-t-xl h-[150px]">
          </div>

          <div class="p-4 bg-white rounded-b-xl"> 
            <h2 class="text-2xl mb-3">{{ chat.product.name }}</h2>
            <p>
              {% if request.user == chat.buyer %}
                Vendedor: {{ chat.seller.username }}
              {% else %}
                Comprador: {{ chat.buyer.username }}
              {% endif %}
            </p>
          </div>
        </a>
      </div>
    {% endfor %}
  </ddiv>
</div>
{% endblock %}

me/templates/me/products.html
{% extends 'core/base.html' %}

{% block title %}Meus produtos{% endblock %}

{% block content %}
<div class="p-10 flex flex-col">
  <h1 class="text-2xl lg:text-6xl text-white">Meus produtos</h1>

  <div class="grid grid-cols-3 gap-5 mt-6">
    {% for product in products %}
      <div class="bg-slate-600 rounded-xl">
        <a href="{% url 'product:detail' product.id %}">
          <div class="flex justify-center">
            <img src="{{ product.image.url }}" class="rounded-t-xl h-[150px]">
          </div>

          <div class="p-6 bg-white rounded-b-xl"> 
            <h2 class="text-2xl">{{ product.name }}</h2>
            <p class="text-gray-500">{{ product.price }}</p>
          </div>
        </a>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

product/templates/product/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ product.name }}{% endblock title %}

{% block content %}
<div class="grid grid-cols-4 gap-6 mt-4 lg:px-10">
  <div class="col-span-2 bg-white rounded-xl">
    <img src="{{ product.image.url }}" alt="{{ product.name }}" class="rounded-xl">
  </div>
  
  <div class="col-span-2 p-6 rounded-xl">
    <h1 class="mb-6 text-2xl">{{ product.name }}</h1>
    <p class="text-gray-700">
      <strong>Price: </strong>{{ product.price }}
    </p>
    <p class="text-gray-700">
      <strong>Seller: </strong>{{ product.created_by.username }}
    </p>

    <p class="text-gray-700">
      <strong class="text-gray-700">Description:</strong> 
      {{ product.description }}
    </p>

    {% if request.user == product.created_by %}
      <div class="mt-6 p-6 bg-white rounded-xl">
        <p>Esse é seu produto!</p>

      </div>
    {% else %}
      <a href="{% url 'chat:detail' product.id %}?buyer={{ request.user.username }}" target="_self" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Entrar em contato</a>
    {% endif %}
  </div>
</div>
{% endblock content %}

product/templates/product/form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
<div class="p-10 lg:p-20 text-center">
  <h1 class="text-2xl lg:text-6xl text-white">{{ title }}</h1>
</div>

<form method="POST" action="." class="max-w-[400px] px-4 mx-auto mb-4" enctype='multipart/form-data'>
  {% csrf_token %}

  <div class="flex flex-col gap-4">
    {{ form.as_p }}
  </div>

  {% if form.errors %}
    {% for field in form %}
      {% for error in field.errors %}
        <div class="mb-5 p-4 rounded-xl bg-red-300 text-white">
          <p>{{ error|escape }}</p>
        </div>
      {% endfor %}
    {% endfor %}
  {% endif %}

  <button class="w-full mt-4 px-5 py-3 rounded-xl text-white bg-slate-600 hover:bg-slate-800">Criar produto</button>
</form>
{% endblock %}